# =======================================================
# WALLPAPER DIRECTORY CONFIG
# Just change the image path inside the "path = " lines below.
# =======================================================

# 1. Preload the image into memory
preload = /home/niko/.config/hypr/walls2.png

# 2. Assign the image to your Main Monitor (DP-5)
wallpaper {
    monitor = DP-5
    path = /home/niko/.config/hypr/walls2.png
    fit_mode = cover
}

# 3. Assign the image to your Left Portrait Monitor (HDMI-A-5)
wallpaper {
    monitor = HDMI-A-5
    path = /home/niko/.config/hypr/walls2.png
    fit_mode = cover
}

# Optional performance tweaks
splash = false       # Disables the text splash rendering on the screen
ipc = true           # Keeps IPC on so you can change wallpapers live via terminal
